### ISSUE TITLE
Add templating tokens into the FedRamp document to allow Masonry to render into it.

### ISSUE THREAD

**Issue by DavidEBest** [opencontrol/compliance-masonry#140]
Here are the relevant links:

* https://www.fedramp.gov/files/2015/03/FedRAMP-System-Security-Plan-Template-v2.1.docx
* https://www.fedramp.gov/resources/templates-3/

**Comment by afeld** [comment]
Nice-to-have:

The FedRAMP docx is already "templatized" in the sense that it contains text like `<Information System Abbreviation>` and `<Date of PA>`. Would be nice to be able to handle those template fields provided by FedRAMP, in addition to the template fields (`{{getControl "..."}}`) that we will be inserting manually.

Similarly, the docx may have a consistent enough structure that we can parse the XML and find where each control should be inserted, which could save a lot of time, especially if they release a new version of the docx. I'm sure we don't want to have to drop the template tags in there manually more than once.

**Comment by afeld** [comment]
Starting an experiment to automate the Go templating here: https://github.com/opencontrol/fedramp-templater

**Comment by afeld** [comment]
I'm starting to think that inserting template tags will be insufficient for the FedRAMP docx (https://github.com/opencontrol/fedramp-templater/issues/10), and that having a FedRAMP-specific Masonry formatter/plugin (https://github.com/opencontrol/compliance-masonry/issues/153) is the way to go.

## Current workflow

...or at least the one we had been working towards.

1. Download Masonry and the fedramp-templater.
1. Run fedramp-templater on original FedRAMP docx, which inserts the template tags.
1. Run Masonry on the templatized docx, producing the final result.

## Proposed workflow

1. Download Masonry and the FedRAMP formatter/plugin.
1. Run `compliance-masonry docs fedramp` on the original (or even a partially-filled) docx.
1. The plugin parses and fills in the file, producing the final result.

The benefit here is that we can do all of the parsing and filling of the docx in a single pass, rather than requiring an intermediate format with special tags inserted for all of the information we want to insert. We can still break the Golang-style docx templating support into its own plugin...it just doesn't make sense for the FedRAMP doc.

**Comment by afeld** [comment]
Closing in favor of https://github.com/opencontrol/fedramp-templater/issues.
